### ISSUE TITLE
"JackTrip was not built with support for Classic mode." on newer MacOS builds?

### ISSUE THREAD

**Issue by asyncmeow** [jacktrip/jacktrip#1349]
Hello!
I use JackTrip for audio-over-IP use within my house (as in, all of the devices are within a few feet of each other). My use case is I have a single pair of headphones and a single microphone, but I need to get audio to several devices, and to do this I'm running a JackTrip server on a raspberry pi with my headphones/mic connected to that (as well as some USB audio interfaces), and using `qjackctl` to manage the audio routing on the raspberry pi. However, after updating JackTrip on my macbook, I can't use it for anything except virtual studio mode. Starting it via the terminal, I see this:
```
❯ /Applications/JackTrip.app/Contents/MacOS/jacktrip
Listening for deep link requests
Log file location: "/Users/pearl/Library/Application Support/jacktrip/JackTrip/log.txt"
JackTrip was not built with support for Classic mode.
SSL Library:  "Secure Transport, macOS 13.4"
```

Is it possible to use JackTrip in a local-only, non-virtual-studio mode on MacOS anymore? Or am I stuck to older versions of JackTrip? Sending audio over the internet like the virtual studio stuff does is the exact opposite of what I want here, especially since I'd have to pay a monthly fee I'm pretty sure for effectively 24/7 use.

**Comment by SynthiaPayne** [comment]
really that should say, "JackTrip was built on Classic Mode."

Classic Mode is audio-only which is where it all began. And from my 
understanding the Classic Mode code has been relatively unchanged since 
JackTrip Labs began developing JackTrip Virtual Studio a few years ago.

With Classic Mode, there is no video or recording and many other 
features of Virtual Studio, and the coding from Classic Mode to Virtual 
Studio is no mean fete and proprietary JackTrip Labs.

Complaining that it should make sure you can use Classic Mode for free 
is just plain unrealistic at this point. Consider what it takes for 
JackTrip Labs to get to Virtual Studio.

Frankly, why do you need the latest version of JackTrip when all you 
need is Classic Mode which as I mentioned is relatively unchanged since 
1.3? hmmmmm?

**Comment by SynthiaPayne** [comment]
or is this a fishing expedition?

**Comment by psiborg112** [comment]
I'm suggesting that it shouldn't be - there should really be an option here. But failing that, then yes, that would probably be the best option once I can get my build environment back to what it should be. (Stupid apple updates.)

**Comment by OConnorStP** [comment]
I agree -- it seems a shame that a project that started so long ago and has such a rich history should be quietly extinguished without a conversation or a plan for carrying it forward.

Aaron, I think the original poster would be well-served by your current releases.  At least they still work fine for me on current Mac silicon and OS.  I'm tempted to just post the link, but...  I dunno.  Your call.

**Comment by SynthiaPayne** [comment]
Although some of my "devil's advocate" comments were taken otherwise, 
they nonetheless opened up communication, and that's a good thing!

Yes, I am using all the flavors of Jacktrip and am delighted to be of 
service to all. That said, I strongly agree that the option to run 
JackTrip in a Classic Mode GUI without Virtual Studio should exist.

Does the "no-GUI" release still allow one to run a JackTrip server or 
client with qjackctl using command line operation? If so, is that a 
viable option for some users?

**Comment by psiborg112** [comment]
Happy for you to share links to them Mike. They're just very out of date at the moment.

**Comment by OConnorStP** [comment]
Great!  Thanks!

Back to the original poster's puzzler.  Aaron wrote the first version of the GUI for Jacktrip in QT and called it QJackTrip.  He's continued to post builds of Jacktrip **[HERE](https://www.psi-borg.org/other-dev.html)** and they should work fine for your Mac and Windows machines.  

A manual install of an earlier Linux version should get you back to Classic mode -- just remember to ignore the insistent "update" messages.  For your rPi you might see what happens when you use "apt install" to load Jacktrip.  Click [HERE](https://www.pgjtt.com/fresh-raspberry-pi-to-jacktrip-start-to-finish/) for a really-old page I wrote about how to do this.

**Comment by asyncmeow** [comment]
Sorry for not really responding so far - GitHub wasn't sending me notifications 😅 

I'll try out the buids from @psiborg112 some time this week once I'm settled in again from traveling. Currently I'm using an older build (2.3.1) on MacOS which works fine for my use case - it just has the reminder popup to update every time.

**Comment by OConnorStP** [comment]
Ah.  Welcome to the legions of JackTrip users who are ignoring those reminder popups.  That's a pretty good approach if it's working for you.  I tend to rename the Jacktrip executable files so they don't get squashed by the update if I inadvertently hit the "update" link.

**Comment by mikedickey** [comment]
I created a [PR here](https://github.com/jacktrip/jacktrip/pull/1360) to fix classic mode missing in OSX builds. Interesting to note that anyone could have done this, but the work fell on me. @asyncmeow you may also like that I just [added support](https://github.com/jacktrip/jacktrip/pull/1359) for arm64 and arm32 Linux builds which work great on Raspberry Pi devices. 

A few other things to think about:
* All the contributions from JackTrip Labs to this project have been published as free open source, under the original MIT license. I encourage anyone who questions the role of JackTrip Labs to just look at the [commit history](https://github.com/jacktrip/jacktrip/graphs/contributors) for @mattahorton @dhing1024 @mikedickey @nwang92 @cchafe @forsythac 
* The only reason classic mode isn't included in certain builds is due to a license conflict with ASIO and GPL. If @psiborg112 were willing to contribute his work under an MIT license, this wouldn't be a problem.
* However, I have always felt that it's very confusing to have two different user interfaces. The qml/qt6 "Virtual Studio" interface quite simply should support all the features of the "Classic" interface (running a standalone audio-only server, and connecting to a remote audio-only server). We just need people to cooperate and contribute more versus picking fights with one another.
* Virtual Studio is COMPLETELY FREE if you don't want all the extra features. It costs real money to run this service and it includes an enormous amount of additional functionality that took many person years (FAR more than this project) to build. But if $49/year (currently on sale for $36.75) is too much to ask to help support the people who created and are maintaining this project, it's of course up to you. You can still use JackTrip without contributing anything. But please have some compassion for people who have been contributing all their time and energy for years to help other people.
* You have always been able to host your own JackTrip server with Virtual Studio. The most recent [docs are here](https://support.jacktrip.com/unmanaged-studio) and any feedback on how to make this better is welcome.

**Comment by mikedickey** [comment]
>  Does the "no-GUI" release still allow one to run a JackTrip server or client with qjackctl using command line operation? If so, is that a viable option for some users?

Yes, all of the original CLI functionality is included in all of the builds.

**Comment by asyncmeow** [comment]
I'd be 100% willing to use - and pay for - virtual studio, if it gets support for hosting local-only servers for scenarios where it simply doesn't make sense to have connections go out to the internet - especially if that includes functionality like "once i am connected, automatically connect the new jack client to these specific devices" so i dont need to do it with tools like wireplumber. On Dec 19, 2024 12:22, mikedickey ***@***.***> wrote:
I created a PR here to fix classic mode missing in OSX builds. Interesting to note that anyone could have done this, but the work fell on me. @asyncmeow you may also like that I just added support for arm64 and arm32 Linux builds which work great on Raspberry Pi devices.
A few other things to think about:
All the contributions from JackTrip Labs to this project have been published as free open source, under the original MIT license. I encourage anyone who questions the role of JackTrip Labs to just look at the commit history for @mattahorton @dhing1024 @mikedickey @nwang92 @cchafe @forsythacThe only reason classic mode isn't included in certain builds is due to a license conflict with ASIO and GPL. If @psiborg112 were willing to contribute his work under an MIT license, this wouldn't be a problem.However, I have always felt that it's very confusing to have two different user interfaces. The qml/qt6 "Virtual Studio" interface quite simply should support all the features of the "Classic" interface (running a standalone audio-only server, and connecting to a remote audio-only server). We just need people to cooperate and contribute more versus picking fights with one another.Virtual Studio is COMPLETELY FREE if you don't want all the extra features. It costs real money to run this service and it includes an enormous amount of additional functionality that took many person years (FAR more than this project) to build. But if $49/year (currently on sale for $36.75) is too much to ask to help support the people who created and are maintaining this project, it's of course up to you. You can still use JackTrip without contributing anything. But please have some compassion for people who have been contributing all their time and energy for years to help other people.You have always been able to host your own JackTrip server with Virtual Studio. The most recent docs are here and any feedback on how to make this better is welcome.

**Comment by mikedickey** [comment]
> I'd be 100% willing to use - and pay for - virtual studio, if it gets support for hosting local-only servers for scenarios where it simply doesn't make sense to have connections go out to the internet - especially if that includes functionality like "once i am connected, automatically connect the new jack client to these specific devices" so i dont need to do it with tools like wireplumber.

Unless I'm missing something here, this has always been available, although only a handful of people have ever used it. We must not be doing a great job communicating about it though so [here is new article](https://support.jacktrip.com/managing-your-own-jacktrip-server) to help get you started. If more people were to use it and provide feedback, we'd be more inclined to put more energy into making it better.

**Comment by psiborg112** [comment]
To be clear, I have no problem with Jacktrip Labs running as it does. The problem though, and we've had this issue before, is that things aren't communicated to end users when some change occurs that will break something that is being used by those in the open source community. If there are builds available with each release that include classic mode for each platform, then that's great! (And in fact, problem solved.) But looking at the releases, I (as a lapsed contributor) can't tell at a glance which ones these are. If it's not obvious to me (without looking through the github workflows) there's no chance it'll be obvious to the average user. Hence this issue being opened in the first place. (And maybe clearer labeling, or an explainer in README.md is all that's needed here, with perhaps something backing that up on the JackTrip page itself for more comprehensive visibility.)

It's great that people can host their own servers with Virtual Studio. But honestly, the process is so much more involved than just using the classic interface to host a server on your own machine. And the same is true of the container process. That's a level of technical know how that you would never dream of asking of most VS users. The whole point of classic mode was to get rid of the need for users to have to confront the terminal. (Even then, they still have to know how to work around their router configuration if they're connecting beyond a local network. But at least no command line.)

If the VS interface was capable of the same things that classic mode is, then that would also solve the issue, and I suspect at that stage we could probably have a discussion about QJackTrip becoming a separate fork. Or maybe that's even the solution now, and something worth discussing? I doubt a classic mode client could even connect to a VS server these days? Maybe there's enough divergence that it doesn't make sense for them to be the same program any more, and they instead have their own separate use cases? It would definitely prevent situations like this arising. It's probably worth thinking about.

**Comment by cchafe** [comment]
_a classic mode client ... connect to a VS server these days?_ 
Just tried that, current main branch, works like a charm.
Yay for interoperability in all things JackTrip!
Chris

**Comment by psiborg112** [comment]
Thanks Chris, good to know.

**Comment by psiborg112** [comment]
Also, just back on the topic of alternative builds, I'm almost back up and running with my laptop. Can't quite get qt5 working properly at the moment on the latest macos, but I do now have a universal build of qt6, so should have a mac universal build out in the next couple of days that will work on 10.14 and later. (Hopefully no one is still stuck on high sierra but if there is interest, and I can get qt5 working, then I can try and make a build of that as well.) And I'll have a new windows build as well, but it'll only have ASIO support via JACK. (There'll be RtAudio, but it'll be one of the other backends.)

**Comment by mikedickey** [comment]
> To be clear, I have no problem with Jacktrip Labs running as it does. The problem though, and we've had this issue before, is that things aren't communicated to end users when some change occurs that will break something that is being used by those in the open source community. If there are builds available with each release that include classic mode for each platform, then that's great! (And in fact, problem solved.) But looking at the releases, I (as a lapsed contributor) can't tell at a glance which ones these are. If it's not obvious to me (without looking through the github workflows) there's no chance it'll be obvious to the average user. Hence this issue being opened in the first place. (And maybe clearer labeling, or an explainer in README.md is all that's needed here, with perhaps something backing that up on the JackTrip page itself for more comprehensive visibility.)

Everything was communicated at the time via the Jitterbug mailing list, release notes, etc. IDK what more you would expect, but it would be great if more people volunteered to help to more rather than expecting other people to do it. I like the idea of having more docs about all the different types of builds. Any volunteers?

> If the VS interface was capable of the same things that classic mode is, then that would also solve the issue, and I suspect at that stage we could probably have a discussion about QJackTrip becoming a separate fork. Or maybe that's even the solution now, and something worth discussing? I doubt a classic mode client could even connect to a VS server these days? Maybe there's enough divergence that it doesn't make sense for them to be the same program any more, and they instead have their own separate use cases? It would definitely prevent situations like this arising. It's probably worth thinking about.

My preference would be to have a single interface, and I would love to see someone volunteer to bring more functionality into what is currently being referred to as "the VS interface." It seems that your preference is to keep working independently on the "classic interface" in your own fork instead. I think if that is the case, it's probably best to remove it from this project versus having effectively dead code that isn't being maintained. In retrospect, it was probably a mistake to include it here in the first place.

**Comment by psiborg112** [comment]
It's not about what I expect. I knew about the decision, and it doesn't impact me because I run my own builds. But clearly it didn't reach others. If you think the current communication channels are adequate, then that's fine. But the fact that this issue was opened suggests that's not the case. (But feel free to take or leave that advice.) Also, I wish I had more time to volunteer, but my time is split between a lot of projects at the moment. And the reality is that there just isn't really the same feeling of community that existed back when this was more of an academic project and there wasn't a single organisation overseeing it. (And once again, that's fine. Things change, and there are definite advantages to the way things are now. But unfortunately it's not really a model that makes people like myself want to jump on board as volunteers.)

Unfortunately, I'm not really interested in the 'VS' interface (in spite of having a hand in it's very early implementation). I just prefer a native widget based solution that puts everything I need in front of me. (And I'm aware my use case isn't the same as that of a lot of people.) Given that all the settings are saved, for repeat performances of a show I did recently all I had to do to get up and running was open the program, enter my password, and hit connect. But once again, my needs aren't the needs of the many, and I would never dream of imposing that on the people who just want to use managed studios. Horses for courses.

Once again, I bear no ill will or animosity towards JackTrip Labs. But I do take umbrage at the insinuation permeating this discussion that people wanting to use an open source project without using the paid solution are somehow mooching. And for the record, the bulk of my contribution to JackTrip does fall under the more permissive MIT license. (Including one whose status was changed ahead of actually getting confirmation on it from me. And which I still agreed to retroactively.) When I started contributing, the code still had blocking loops that wouldn't have played well with a then non-existent interrupt handler, let alone a responsive user interface. Networking involved some weird work arounds that were gotten away with on an IPv4 stack, but that wouldn't transfer to an IPv6 one. (And they certainly didn't use the kernel polling mechanisms that they now do - and you saw how much of a performance increase that brings.) There was no mechanism for a client to signal it was disconnecting. And the auto patching didn't play well with other JACK applications. Just to get to the point of being able to introduce a GUI took major restructuring work that touched upon huge sections of the code. All of it undertaken as a passion project, with no expectation of getting anything back, and happily released under the prevailing MIT license. (And no, I'm not looking for some sort of medal. Plenty of others have contributed a lot to the project too, including the JackTrip labs team. It would just be nice for that contribution to not be minimised.)

**Comment by mikedickey** [comment]
@psiborg112 I didn't mean to minimize your contributions in any way as both I and many others do really appreciate them! I also have contributed an enormous amount of work to this project without expecting or receiving anything in return, so I can certainly relate far more than I think you know!

JackTrip started out as an academic project, but has since evolved to serve a much broader audience. As I mentioned before, the virtual studio service is and always has been freely available, and tens of thousands of people have benefited from it. I don't feel that any of them are "mooching" or should be obligated to contribute to open source. Using it makes a lot of things easier (whether you are paying for the extra features or not), and I like to point out opportunities that I see to make people's lives easier. If there are gaps in knowledge or documentation, I seek to address them.

The single organization overseeing the virtual studio service was started by @cchafe and I as a non-profit and currently functions as a public benefit corporation (another type of organization committed to bettering society). I respect everyone's choice to volunteer or not, but those who do so can benefit many more people. If this isn't something you are aligned to, it is certainly your choice, but it would be tragic if this community were to lose people such as yourself simply over miscommunication.

Perhaps it's overly optimistic of me to imagine a single interface that serves everyone well. I think it's great that JackTrip is used in so many different ways, and different interfaces may be necessary for different audiences. Perhaps the mistake here was trying to serve all of them via a single package/download. I've since learned from experience that even as little as a "Use Classic Mode" link at the bottom has sent too many people down a path they were very ill suited for.

Perhaps a good next step would be to create a separate "jacktrip/qjacktrip" project under this github organization and moving all of the QJackTrip code into it, with a submodule dependency on jacktrip/jacktrip? That way it would have its own independent CI, releases and packages, and separate downloadable artifacts (without them being mixed into the ones currently generated under jacktrip/jacktrip), while still sharing source and everyone's ongoing contributions to the core project? If this idea resonates with you, I'll volunteer the extra time to set it up.

**Comment by psiborg112** [comment]
It's a generous offer, but given that it'll probably just be me maintaining it, it's probably overkill compared to a regular fork. (And I should have time to set one up sometime in the next month.) Especially since I'll likely just be uploading locally built releases rather than having github generate them. (It means I can keep making things like universal builds without having to struggle with getting the CI to handle it.)

**Comment by asyncmeow** [comment]
Haven't been keeping up with the thread too much, but I'd be willing to try and help get universal MacOS builds in CI, if that's the blocker? I'm not too familiar with Github Actions, but I've been wanting to learn it and that might be a good opportunity. On Dec 26, 2024 18:20, Aaron Wyatt ***@***.***> wrote:
It's a generous offer, but given that it'll probably just be me maintaining it, it's probably overkill compared to a regular fork. (And I should have time to set one up sometime in the next month.) Especially since I'll likely just be uploading locally built releases rather than having github generate them. (It means I can keep making things like universal builds without having to struggle with getting the CI to handle it.)

**Comment by psiborg112** [comment]
I don't think anyone would say no to someone offering to modernise elements of the build system. I think the important thing here is that, whatever the path forward, there will still be a way to access the classic mode GUI (even if that's through a separate app) that will hopefully serve the interests of users of both interfaces.

**Comment by mikedickey** [comment]
We already generate universal builds of JackTrip for OSX, _and_ we already generate release builds of JackTrip that include the classic mode / QJackTrip interface for all platforms. As I stated before, it's included in all release artifacts except those that have "signed" in the name.

I'm going to plan on removing these extra builds and the classic mode / QJackTrip interface entirely from this repository, since:

* It sounds like @psiborg112 's preference is to fork maintain QJackTrip as a separate project. I think there's no point in trying to maintain it in two different locations.
* Offering two different user interfaces is clearly creating confusion.
* Having the extra builds seems to serve no purpose other than create confusion.
* License conflicts. This would allow us to return entirely to MIT and eliminate the confusion and issues with some things being MIT and others being GPL.

**Comment by psiborg112** [comment]
@mikedickey, Good to know on the universal front. (Sorry, the x86 in the package names is confusing. Might be worth changing to universal?)
