### ISSUE TITLE
add OSX jacktrip installer 1.2.1

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip/jacktrip#158]
(reinforcing @wholenotes request)
Please add installer to version 1.2.1 for OSX.
the linked page on readme.md only contains 1.2.

this refers also to #89

**Comment by mikedickey** [comment]
+1 and to ensure this isn't a continuing problem, we should update Travis to automatically produce new installer packages whenever the main (and, ideally also dev) branches are updated.

**Comment by wholenotes** [comment]
Temporary link to JackTrip 1.2.1 installer:
https://www.dropbox.com/s/jb7vh9oiew50cm6/jacktrip-macos-installer-x64-1.2.1.pkg?dl=0

Tested on Catalina.  I would welcome feedback on whether this works for older 64-bit versions of Mac OS X.

OS X will probably block the installer because I didn't sign it with a Developer's certificate, so these steps should be necessary after you click on the file in the directory where it was downloaded:
Cmd + Spacebar, and type in: Security & Privacy >> Go to the General tab
Click on Allow anyway where it tells you "jacktrip" was blocked from use because it was not from an identified developer
and maybe click on the lock icon (something like that)
Click Open if you encounter another prompt telling you "jacktrip" cannot be opened.

Open a terminal window and type: jacktrip -v
which should return: JackTrip VERSION: 1.2.1

**Comment by omarcostahamido** [comment]
thank you @wholenotes .
I propose merging #163 

Best

**Comment by gregkowalski66** [comment]
Mojave 10.14.16
I have zero experience with terminal.
Installed acktrip-macos-installer-x64-1.2.1.pkg  
I followed instructions for terminal and typed jacktrip -s 
Got the following error: 

dyld: Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/bin/jacktrip
  Reason: image not found
Abort trap: 6

Is there something missing or am I doing something wrong. 

Thanks.

**Comment by wholenotes** [comment]
Do you have JACK installed?

**Comment by gregkowalski66** [comment]
Yes. It's up and running.

**Comment by ntonnaett** [comment]
You are experiencing #104 
Please comment there.

**Comment by wholenotes** [comment]
Thanks, Nils.
Yes, I just did a test following these instructions on Mojave, and I was able to run jacktrip -s: https://ccrma.stanford.edu/software/jacktrip/osx/index.html

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
