### ISSUE TITLE
Cannot start JackTrip: Library not loaded

### ISSUE THREAD

**Issue by andersvincent** [jacktrip/jacktrip#182]
I installed Jack 1.9.16 using the installer for macOS. After that I installed jacktrip 1.2.1 using the installer package for macOS.

I opened qjackctl and pressed start. After this I tried to execute `jacktrip -s` but I received the following error:

```
dyld: Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
Referenced from: /usr/local/bin/jacktrip
Reason: image not found
```

I am running Mojave(10.14.6). I seem to not be the only one that has this problem, but the only other issue I found was related to homebrew, and I did not install Jack using homebrew. Is there any other build that potentially could fix this? Not much of a hacker myself. Help would be highly appreciated.

**Comment by jasonbrancazio** [comment]
I'm having the same issue. The maintainer of jack2 recommends in this github [issue](https://github.com/jackaudio/jack2/issues/640) to recompile jacktrip using these args: -L/usr/local/lib -ljack

I'm thus currently looking for the best documentation in this codebase about how to recompile jacktrip and supply these arguments. Can anyone point me in the right direction?

I see this INSTALL.txt but I'm not sure the ./build step accepts arguments. I plan to try it out and see.
https://github.com/jacktrip/jacktrip/blob/main/INSTALL.txt#L93

**Comment by jasonbrancazio** [comment]
update:

following the instructions in INSTALL.tx and running `./build -L/usr/local/lib -ljack` got me past the `Library not loaded` error. I don't know whether supplying those arguments made a difference, or whether merely compiling my own version of jacktrip was sufficient.

I recommend avoiding the `brew install qjackctl`step in INSTALL.txt because the jack2 binary distribution comes with a newer version of it. In addition, as of this writing, `brew install qjackctl` installs jack v 0.125.0_4 in the Cellar and may screw up some jack-related symlinks. (I still have to investigate this further.)

I'm now able to run a jacktrip server on my LAN on an old laptop running OSX 10.9 (Mavericks) with an old JackOSX and connect to it as a client with the newly compiled jacktrip on Catalina, and vice versa.  I ran the hub server on Catalina and made a successful connection too. The ultimate test will happen tomorrow when I jam with a friend. :)

**Comment by daniels220** [comment]
I was able to follow the instructions in INSTALL.txt and get a working jacktrip, but `brew install qt5` took _hours_, and I just determined that the `jacktrip` binary I built will not run on another machine without Homebrew's qt5—yet the one from the official installer _will_, it's just that it also needs the old JackOSX instead of the new jack2. Is there any way to build a binary that doesn't have this runtime dependency on Qt? I'd like to build the binary on a machine that already has Homebrew (and has already spent the hours compiling Qt) and distribute it to others who I'll be playing with...

**Comment by ntonnaett** [comment]
This should be fixed in the upcoming release.
