### ISSUE TITLE
Make Jack library paths configurable on Windows

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#234]
Currently paths to Jack library on Windows are [hardcoded](https://github.com/jacktrip/jacktrip/blob/main/src/jacktrip.pro#L100) for a previous version of Jack.

For Jack 1.9.11 (and maybe few others) they should be (as specified currently):
```bash
  INCLUDEPATH += "C:\Program Files (x86)\Jack\includes"
  LIBS += "C:\Program Files (x86)\Jack\lib\libjack64.lib"
  LIBS += "C:\Program Files (x86)\Jack\lib\libjackserver64.lib"
```

For Jack 1.9.17 (and maybe .15 or .16 as well) they should be:
```bash
  INCLUDEPATH += "C:\Program Files\JACK2\includes"
  LIBS += "C:\Program Files\JACK2\lib\libjack64.lib"
  LIBS += "C:\Program Files\JACK2\lib\libjackserver64.lib"
```

I think that one solution would be to replace `C:\Program Files (x86)\Jack` with a string that's configurable when running the script. I'm not familiar enough with the structure of qmake files to suggest the exact solution at this time.

(I also tried just adding the new paths and that does not work for the `LIBS`).

**Comment by ntonnaett** [comment]
Can we use pkg-config if we build with mingw?

**Comment by dyfer** [comment]
I don't know. I know little about pkg-config in general, even less so how it works on Windows, and I don't know if Jack on Windows provides pkg-config entries...

**Comment by ntonnaett** [comment]
When I use meson with mingw, Jack (installed with chocolatey) will get found. When I use meson with MSVC Jack is not found. So I think pkgconfig is fine, because we weren't able to build with MSVC at all. You could run meson in your local Mingw setup (with Jack from jackaudio.org) and see if it finds jack with pkg-config.

**Comment by dyfer** [comment]
Ah, I see. 
I was referring to "regular" installs of Jack, using the installer, not package manager. I believe we need to support building with "regular" Jack installation. I don't think it provides pkg-config entries, but I might be wrong.

**Comment by ntonnaett** [comment]
The way you install jack shouldn't make any difference. Jack has a pkg-config file on Linux and MacOS. I will install Windows in some weeks and test this. Hardcoded paths lead to problems. QJackTrip's cmake build is broken on Fedora because Ubuntu paths are hardcoded.
Some side note: pkg-config gives you also the necessary compile and linker flags for your dependencies.

**Comment by ntonnaett** [comment]
https://jackaudio.org/faq/making_a_jack_app.html
https://github.com/jackaudio/jack2/issues/287

**Comment by dyfer** [comment]
Okay, so it should be there... still, pkg-config is an additional dependency to install on Windows, AFAIU.

**Comment by ntonnaett** [comment]
When I tried the meson build with mingw first, I think it found jack through pkg-config. But I could be wrong. As I mentioned I will check this when my Windows system is ready. And the additional pkg-config dependency is not a problem in my opinion because it's only a dependency for developers, not for the end user. And if you already installed mingw, pkg-config should be no big deal.

When I understand the second link I posted correctly, Jack with MSVC isn't working yet…?!

**Comment by dyfer** [comment]
> And if you already installed mingw, pkg-config should be no big deal.

I might be wrong, but I think my mingw came with qt and I didn't have pkg-config. 

> When I understand the second link I posted correctly, Jack with MSVC isn't working yet…?!

Maybe, idk. There are some linking issues mentioned earlier in the thread, does that mean that we can't link with pre-build (MinGW) Jack if we build JT with MSVC? 
This was one of the issues with JackRouter - it's a library that MSVC-compiled apps would crash when trying to load. This has since been solved it seems, but I'm not sure how. I'm out of my depth on these things on multiple levels (c++, linking, Windows-specific dev stuff)...

**Comment by dyfer** [comment]
BTW I'm supporting to fix this in a more permanent way, but for the time being #239 addressed this for the two now-available versions of Jack, AFAICT.

**Comment by ntonnaett** [comment]
Yes, I think we can close this for now. The MSVC build is another issue and actually is a new goal.
