### ISSUE TITLE
OSX install instructions out of date

### ISSUE THREAD

**Issue by ginacollecchia** [jacktrip/jacktrip#30]
There is no folder "jacktrip" in the jacktrip folder, so the first instruction "cd jacktrip/jacktrip/src" doesn't apply.

**Comment by tmm2018** [comment]
**dear @ginacollecchia:**
- *i had the same problem that you had.*

**the problem is related to the fact that:**
- *the latest release of jack trip for macOS took place in 2015*
- *the source is being maintained, but there wasn’t like an official release since then.*

**Here’s what you can do, to overcome this issue:**
- **a)** *installing an old version of fedora in a VM*
- **b) *installing an older version of macOS, preferably MacOS El Capitan, either inside a VM, or in a fresh side install;*

**Regarding <a> -> installing an old version of Fedora in a VM:**
- *just check which is the latest version of macOS that hosts planet ccrma;*
- *find it somewhere on the internet;*
- *make a fresh side install, or make a VM;*
- *install it;*
- *install jackrouter;*
- *install jack trip;*
- *you should be good to go*

**Regarding <b> -> installing an older version of macos:**
- *Everything is the same.*

**You will need:**
- *el capitan*
- *jackrouter 0.92 b3*
- *latest jack trip release*
- *you can find it here: https://github.com/jcacerec/jacktrip/releases*

**The reason why this doesn’t work in either Sierra or High Sierra is:**
- *there are some broken paths in the system, due to its developments*

**Please notice that:**
- *in my case, even with sudo command, i wasn't able to modify my usr/bin folder to put there the jacktrip command*
- *i had to run cd jacktrip/bin && ./jacktrip (after using jackserver), which is kind of weird because it should*

**Comment by GGBoCa** [comment]
Hey !

I know it's a quite hold post, but I found it yesterday when I was trying to install jacktrip, and I finally found a solution. If it the same for someone else : [the link](https://ccrma.stanford.edu/software/jacktrip/osx/index.html).

There is a simple installer working on osx 10.14.

Tschüss
GG

**Comment by ginacollecchia** [comment]
Thank you!

**Comment by ntonnaett** [comment]
Duplicate of #60
