### ISSUE TITLE
Limiter license mismatch

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#358]
https://github.com/jacktrip/jacktrip/blob/551cb18b273085613c23dd82751672a567ecb974/faust-src/limiterdsp.dsp#L8

If this is the current base of our c++ code, all builds of JackTrip are GPLv3. We should document this before the release.
Transpiling a new C++ file would override all changes we did to that file.

**Comment by dyfer** [comment]
(notes from the dev meeting Jul 14)
- let's add a compile switch to switch between GPL-licensed and MIT-licensed limiter (qmake/meson/cmake)
- it can default to GPL limiter
- (Marcin: I'd explicitly specify that option in the build system in so that we know that our automated builds using the GPL version, which has been used already for a while AND we are building with GUI which makes everything GPL)
- document building a MIT-licensed jacktrip (no GUI, no weakjack, MIT limiter)

**Comment by ntonnaett** [comment]
For whom or what are we doing this effort of maintaining a MIT version? This feels quite unnecessary without knowing.

**Comment by dyfer** [comment]
> For whom or what are we doing this effort of maintaining a MIT version?

Maybe @cchafe can answer that?

**Comment by dyfer** [comment]
I started looking into this and it looks like this `jacktrip/faust-src/limiterdsp.dsp` file needs to be processed with faust in order to generate a different limiter into `limiterdsp.h`. This means that we can't change this at compile time, we'd need to run faust to generate a different limiter. 
It seems that we also use freeverb and zita which are LGPL, so a more permissive license than GPL, but what does that mean for the rest of the project? Do we need switches for them or are they implicitly compatible with MIT?
So, would we want to generate two limiters (MIT and GPL) using faust, and switch between them in our build systems?

**Comment by ntonnaett** [comment]
As nobody came forward to explain why this is necessary, I don't see a reason for that. Just make JackTrip GPL. It's much easier.

LGPL would make JackTrip LGPL. You can't make a closed source project out of it then (only as a service...).
