### ISSUE TITLE
Remove RTAudio warning (or make friendlier)

### ISSUE THREAD

**Issue by forsythac** [jacktrip/jacktrip#477]
With the inclusion of RTaudio, more and more people are using the JackTrip Core app without having ever installed JACK

Right now, we give a very informative but intimidating error message to new users:

![image](https://user-images.githubusercontent.com/3578658/150874429-3a98f660-9094-4f15-8503-be850454fa0a.png)

We've had a decent number of people think that their installation was not successful due to this message. What's the value of this warning? Can we remove it, since everything is working as expected?

**Comment by ntonnaett** [comment]
They would probably wonder why some features don't work. But I must say that message looks bad.

We already have places where the gui just changes according to what backends are available. Maybe it's sufficient if we remove the hub server mode for RtAudio? Maybe this is already the case? Maybe we can add a help button somewhere to explain what they are missing out without JACK.

**Comment by psiborg112** [comment]
I'm happy for someone to make it friendlier if they want, but I don't think it should be removed. I understand that a lot of people don't need JACK, but there are plenty of use cases where it's still important, and I've lost so much time to troubleshooting issues with my students because they just totally ignored that warning message.

And yes, we currently remove the hub server mode choice if only RtAudio is available.

**Comment by psiborg112** [comment]
If you do want to remove it, can I request that whoever does it simply disables it from running by using a preprocessor directive so that I can keep it in my builds.

```
#ifdef NO_JTVS
(code that shows the warning)
#endif
```

**Comment by SynthiaPayne** [comment]
Today I was helping someone who a) never got passed that RtAudio 
warning, b) had no idea what RtAudio is, c) thought the error message 
meant that his computer would not run the app, and d) thought that the 
error message meant that the app was not installed. All totally 
understandable for an inexperienced user.

I wonder if some explanation of the difference between JACK and RtAudio 
might help. Like, "JackTrip needs a backend app to hand off the audio it 
will send and receive from the internet. This backend app can be RtAudio 
or JACK, however, the JackTrip server mode is only available with JACK."

or something like that...

synth

**Comment by psiborg112** [comment]
If the main concern is that people don't think the app will run then we should just address that directly. Might I suggest:

An installation of JACK was not found. JackTrip will still run using a different audio library (RtAudio) but some more advanced features, like the ability to run your own hub server, will not be available.

(If you install JACK at a later stage, you can re-enable these features by changing the settings in the Audio Backend tab.)

**Comment by ntonnaett** [comment]
I like that. But the common user wouldn't understand what an audio library is. Maybe something similar to: "You are running JackTrip with a reduced set of features because the JACK audio server is missing. If you need those additional features, you can download JACK [here](https://jackaudio.org)."

Maybe list what features are missing without JACK…

**Comment by psiborg112** [comment]
They probably won't understand exactly what an audio library is, but they should hopefully be able to get the gist of it from context. The important thing is that if they don't entirely get what's going on (and they don't necessarily need to) then they're reassured that the program will still run. And that it's only more advanced features that they're missing out on. (I think your wording is ok, but it reads a little more pessimistically and might still cause some concern.) I think it's important to mention RtAudio here because ultimately this is the setting they're going to need to look for if they want to switch back to JACK in the future.

**Comment by psiborg112** [comment]
(We could also just use backend instead of library.)

**Comment by ntonnaett** [comment]
Let's use backend instead of library. What do you think about not mentioning RtAudio?

**Comment by SynthiaPayne** [comment]
The backend term matches the wording in the app but new users still might be confused and unaware if JACK or what it does. I think that an error message that interrupts using the app after first installing it is problematic. 

Synth

**Comment by mikedickey** [comment]
What are the more advanced features that people would be missing out on, if they don't use JACK? AFAIK, this is only:

1) you cannot run a hub server
2) you cannot use JACK to manage patching of audio

Is more I am missing?

The only people who would ever care about (2) are people who already have JACK installed, and therefore will never see the warning.

There is extremely small population out there who fits into (1), well under 0.1%, so the startup message seems way more disruptive than it is worth. Perhaps there is a different way we can notify them that the hub server functionality is unavailable because jack is missing? For example, if they click on "hub server" in the dropdown it could display the warning then?

**Comment by mikedickey** [comment]
Also I don't know if this is related or not, but on Windows 11 it now also opens a terminal window with the message:

```
*** WEAK-JACK: initializing
*** WEAK-JACK: libjack was not found
```

Which is even more confusing and disruptive than before ;-)

**Comment by SynthiaPayne** [comment]
Regarding #2, patching of audio, is a frequently asked question among 
those who want to use the core app - that is, how to send JackTrip audio 
to other places, whether or not someone is familiar with JACK. This can 
be done without JACK, but does involve other apps.

Regarding #1, perhaps in the Virtual Studio community the numbers of 
those interested in running their own Hub Server are very low, however, 
in the core app community the numbers are far greater.

synth

**Comment by psiborg112** [comment]
I think the way that we're probably headed here is that the warning will remain in my build with the new wording that I've proposed and won't exist in the official build, but I think in the process we could well be making life more difficult for our more intermediate and advanced users.

**Comment by psiborg112** [comment]
Also, I can't test on windows 11, so don't know why that terminal window isn't closing properly in that case. Either the way the freeconsole() command functions has changed or the libraries that deal with parent process IDs have.

**Comment by psiborg112** [comment]
Does the console show only those two messages, or does it continue to output stuff when you start a connection?

**Comment by psiborg112** [comment]
Also, to pick up on what Synthia said, the needs of the Virtual Studio community are not the needs of the JackTrip community, and both of those features are things that are asked about and used on a regular basis.

More advanced and intermediate users, the type who are absolutely interested in both of those features (particularly patching), don't start out that way. It's a learning process. And along the way, they can make mistakes. One of them is installing and running JackTrip before JACK is installed, which causes the program to fall back to the RtAudio backend. Now for basic users who have no interest in doing anything other than sending whatever comes into their mic across the network, that's not a problem. But for those who want to learn more, who want to extend their skills and abilities and to explore the actual potential that the software offers, silently changing settings in a way that limits functionality throws an additional roadblock in their path. (This is not a hypothetical - as I mentioned above this has been a very real issue for students of mine who haven't paid attention to that warning.)

As a user, the most infuriating problems I've had to fix (and often those that take the longest to diagnose) are always those that result from a program thinking it knows better than I do and changing settings without warning in an attempt to be helpful.

**Comment by ntonnaett** [comment]
I don't like the idea of removing this warning completely. JackTrip should work for all users. Can we put this in a banner in the backend tab?

**Comment by psiborg112** [comment]
@ntonnaett we should probably do that anyway. I've just realised that outside of this warning we don't have anything that tells the user what limitations there are in RtAudio mode. I can add it as a label in the backend tab. But if we just silently change backends, there's no guarantee that the user will see it.

**Comment by forsythac** [comment]
I really like the idea of putting it in the Audio Backend tab- that way people who start with RTaudio (and dismiss the warning) will be able to upgrade their skills in the future by investigating the Audio Backend options.

**Comment by mikedickey** [comment]
I wonder if it may be best to address this in the context of introducing a "simple" or "virtual studio" mode? Startup FTR gives you choice between that vs "advanced" mode (we can call them whatever). If you choose simple, it never warns you about JACK not being installed. If you choose advanced, it shows you the warning if JACK is not installed. What would you think about that?

**Comment by SynthiaPayne** [comment]
That sounds good to me too. I was just thinking that something like, 
"For more information, please visit https://jacktrip.github.io/jacktrip/"
but there is nothing there pertaining to RtAudio and/or JACK. It would 
be helpful to refer users to where they can learn more about JackTrip's 
use of RtAudio and JACK.

**Comment by SynthiaPayne** [comment]
> I wonder if it may be best to address this in the context of introducing a "simple" or "virtual studio" mode? Startup FTR gives you choice between that vs "advanced" mode (we can call them whatever). If you choose simple, it never warns you about JACK not being installed. If you choose advanced, it shows you the warning if JACK is not installed. What would you think about that?

**Comment by SynthiaPayne** [comment]
Terms like "simple" and "advanced" are very general and users are unaware of what it really means. 

There is a 'tooltip' that appears when hovering over the dropdown menus for RtAudio, etc, which is very helpful. Perhaps including a URL for learning more would give users additional help.

synth
