### ISSUE TITLE
1.5.1: Fails to properly locate rtaudio

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#483]
RtAudio installs the header ```/usr/local/include/rtaudio/RtAudio.h``` and the pkgconfig file ```/usr/local/libdata/pkgconfig/rtaudio.pc``` but the cmake build fails:
```
In file included from /disk-samsung/freebsd-ports/audio/jacktrip/work/jacktrip-1.5.1/src/Settings.cpp:67:
/disk-samsung/freebsd-ports/audio/jacktrip/work/jacktrip-1.5.1/src/RtAudioInterface.h:41:10: fatal error: 'RtAudio.h' file not found
#include <RtAudio.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by psiborg112** [comment]
Once #484 is fixed, I would recommend using qmake to build because that's been tested with FreeBSD previously. That said, I'm not sure what the current status of it is because I don't know how well it's been maintained on that front. (Or meson might be the go. @ntonnaett, does meson work for FreeBSD builds?) The cmake configuration isn't officially supported and definitely needs to have some work done on it for it to run on machines that aren't just my computers.

**Comment by ntonnaett** [comment]
It should work if the `__linux__` macro is set. But the desktop integration would be missing. It would be great to have somebody from the FreeBSD community who would keep in touch with us to test and fix this. I'm not at all familiar how those ports are handled. Wouldn't it be better if jacktrip just builds on BSDs without changes?

**Comment by yurivict** [comment]
Defining ```__linux__``` doesn't work on BSD because of conflicts.
