### ISSUE TITLE
Qjackctl and Jacktrip versions for Mint 20.3

### ISSUE THREAD

**Issue by a7cross7** [jacktrip/jacktrip#485]
What are the most recent versions of Qjackctl and Jacktrip that should be run on Mint 20.3? When I run what is suggested, "sudo apt-get install qjackctl" it gives me version 0.5.0, which I understand is not what I should be installing. I am also using Jacktrip version 1.1, which I understand is not the most recent. I have been having audio distortion issues when I try to connect to a Jacktrip hub server. Thanks for any assistance.

Andy Cross

**Comment by ntonnaett** [comment]
qjackctl 0.5.0 was already outdated when Ubuntu 20.04 was released. That's what Linux Mint 20.3 is based on. Why?

As this isn't a jacktrip issue, I kindly ask you to ask your distribution's package maintainer to make an update exception for jacktrip. I'm not sure if this is necessary for qjackctl as long as you don't have any problems. There should be a big Linux Mint update in summer.

As I stated before you can also download the latest jacktrip version from our releases page.

**Comment by a7cross7** [comment]
I'm sorry. I really don't understand the whole politics of this.

I'm just trying to get this netbook running an operating system that will
support running Jacktrip. Do you recommend another operating system than
Mint and, if so, is this little netbook likely to be able to run it? I can
try to approach the distributers of Mint, but I'd rather just get a system
running on Linux that will also run Jacktrip and keep the necessary
associated software updated to run the current versions of those software
packages.

My appologies for any bother.

Andy Cross

**Comment by psiborg112** [comment]
The best place to ask for help on these sorts of things is probably somewhere like the JackTrip Users Group on Google Groups. (You can find it here: [https://groups.google.com/g/jacktrip-users](https://groups.google.com/g/jacktrip-users)) The Issues section of GitHub is a place for people to bring bugs in the program to the attention of the developers. So issues that need to be fixed with a change to the code rather than a change to configuration. And we can only measure bugs against the latest release, because otherwise there's every possibility that they're issues that we've already fixed.

So, what I'd recommend you do is to do what @ntonnaett has suggested, which is to download the latest version for linux from the [releases page](https://github.com/jacktrip/jacktrip/releases). If you still have problems with it, ask around for help first on the users forum. And if it looks like something is broken with the program itself, that's the time to post about it here.

All the best,
A

**Comment by a7cross7** [comment]
Understood. Thanks!
