### ISSUE TITLE
libjack warning on Windows 11

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#539]
On Windows 11 using rtaudio (no jack installed), running jacktrip (with GUI) will also cause a terminal window to open with this message:

```
*** WEAK-JACK: initializing
*** WEAK-JACK: libjack was not found
```

Although one can close the window and continue using JackTrip, the window doesn't go away automatically (as I understand it may on Windows 10). It's pretty scary and confusing, and with Windows 11 adoption/upgrades on the rise, increasingly becoming a bigger problem.

**Comment by ntonnaett** [comment]
Weakjack outputs to stderr. It's a C library. Can we override this?

**Comment by psiborg112** [comment]
The warning is easy to get rid of. We just need to set NDEBUG as a compiler definition. The console window, I have no idea about and I don't have Windows 11 to test with.

**Comment by mattahorton** [comment]
The core of the issue with the console Window is that Qt 5.15.2 open source (and 5.15.3 open source which has near zero documentation online) do not support detection of Windows 11 using the `#ifdef _WIN32`. And it's unlikely they will as Qt is moving toward 6.2+ and only _officially_ supporting Windows 11 there. 

We have a line that calls `FreeConsole()` if the app is running on Windows. That fires on any Windows below 11, but isn't firing on 11.

**Comment by ntonnaett** [comment]
The `#ifdef` can't be the culprit because it's done by the preprocessor and doesn't end up in our release build for windows. There are two possibilities. isRunFromCmd() is true on Windows 11 but not below, or FreeConsole() doesn't do the same on 11 compared to below. If you mean with firing that FreeConsole() is invoked then it must be the first.

Maybe the semantics changed from verb to adjective…

**Comment by psiborg112** [comment]
One thing that you could test would be to remove the conditional around FreeConsole() so that it's always called. That will check which part of the code isn't working. Also, if you run it from the command line you'll be able to see whether the FreeConsole call is actually doing anything. If nothing from cout gets printed to the command line, then we'll know that FreeConsole() now just detaches the process from the console without actually closing the window. (And if you see stuff from cout, then you'll know it's most likely doing nothing.) I would test this myself, but don't have Windows 11.

**Comment by mattahorton** [comment]
I actually think this is because Windows Terminal is the default terminal on W11. That process name is `wt.exe` and I've added that to the conditional. I also don't have W11, but @mikedickey does and I've been having him test for me 😅

**Comment by psiborg112** [comment]
Yeah, it won't be that. The reason for checking the parent process is so that we can keep seeing debug messages if jacktrip is deliberately run from the command line. The absence of wt.exe in the checks there will just mean that the console will still be detached with FreeConsole if run from windows terminal.

**Comment by psiborg112** [comment]
So it would only be a false positive due to a change in how windows deals with the process info functions we're using that could be causing the issue there.

**Comment by psiborg112** [comment]
Otherwise it's more likely related to the behaviour of FreeConsole. (And why I can't find documentation on this anywhere is beyond me.)

**Comment by ntonnaett** [comment]
https://docs.microsoft.com/en-us/windows/console/freeconsole

Maybe weak-jack allocates a new console on Windows 11?

**Comment by mattahorton** [comment]
I've now run it on windows 11 and haven't gotten this terminal myself.

**Comment by psiborg112** [comment]
That's good, but also slightly annoying because this could be one of those annoying, intermittent issues that's difficult to track down. Are you building it with NDEBUG set? And if you are, does the terminal appear if you build without NDEBUG? Maybe windows 11 won't automatically close a console window when detached if anything has been output to it?

**Comment by mattahorton** [comment]
I am. 

Turns out this happens only if you've got Windows Terminal Preview installed. It was in a specific environment.

The NDEBUG flag is in `virtualstudio` to address the debug prints, but the terminal shouldn't be an issue for most users.

**Comment by ntonnaett** [comment]
Is it a missing feature of Windows Terminal Preview and will get fixed there? Won't this become the default terminal at some point?

**Comment by mattahorton** [comment]
It could also be something like if Windows Terminal Preview is not installed with the OS the OS can't point a `FreeConsole()` call to it. We really don't know. 

As it stands, I think the thing to do is close this issue and [report a bug on the Windows Terminal repo.](https://github.com/microsoft/terminal)

**Comment by mattahorton** [comment]
I believe this is handled. Shall we close?

**Comment by mikedickey** [comment]
This is resolved in dev

**Comment by psiborg112** [comment]
Did anyone do anything to fix it though? Did it resolve itself? (Was there a windows update that took care of things?)

**Comment by mikedickey** [comment]
Microsoft finally pushed out an update with this fix! It's available via the latest release in the Microsoft Store, and also I think they may have pushed it out to people via auto updates.

For people who are still afflicted with the problem, I've added a more friendly message to the window with instructions on how to fix it. https://github.com/jacktrip/jacktrip/pull/1064
