### ISSUE TITLE
Window decoration misbehaving in virtual studio mode

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#550]
If I drag and hold the window the window decoration looks like it loses focus.
Probably something about updating the decoration. The close button doesn't animate or is stuck. That's only in virtual studio mode. When switching to the old interface the window decoration behaves correctly.

Fedora 35, Gnome, Wayland

_Originally posted by @ntonnaett in https://github.com/jacktrip/jacktrip/issues/545#issuecomment-1118890397_

**Comment by ntonnaett** [comment]
In classic mode the window loses focus only when moving. That isn't right either. Maybe fixing that fixes the weird behavior in virtual studio mode too.

**Comment by ntonnaett** [comment]
This should be fixed before we make the 1.6.0 release. Most major distributions default to wayland.

**Comment by psiborg112** [comment]
I don't use wayland for precisely these sorts of reasons - there are still too many issues with it. Which means I'm probably not the right person to fix any wayland issues.

**Comment by ntonnaett** [comment]
I have more problems with X11 than I have with wayland nowadays. But maybe that's the case because I avoid qt apps. I don't have time to fix this.

I just checked the behavior of kate. What looks like the window's losing focus when moved (classic mode) seems to be correct behavior…

**Comment by ntonnaett** [comment]
I just checked what the situation with Qt6 would be. The window doesn't lose the focus in classic mode anymore when moving. The area around the window for changing the size is bigger. Very good! But everything else is worse. When changing the size in virtual studio mode the content of the window becomes plain white. The scrollbar isn't draggable. 

I've created a draft PR for the qt6 port: #557 

What might be interesting for this issue is that at least the close button behaves correctly as long as the 'logging in…' screen is active.

**Comment by psiborg112** [comment]
I just switched into a wayland session on my laptop, and I don't see any of these issues that you're reporting. Running Debian unstable with KDE. Since last time I looked at wayland, it's looking much better. (Desktop scaling works without blurry fonts.) But there are still some missing plasma features. But, none of the issues that you've reported here.

**Comment by psiborg112** [comment]
I mean, I don't think there's much that we could do to fix this anyway. Our code doesn't do anything to specifically change the window behaviour. The most we do is set a minimum window size in virtualstudio mode. Window decorations are surely the domain of the window manager, and they're working fine under kwin.

**Comment by psiborg112** [comment]
(I should clarify that this is for the qt5 version. Have not tested the qt6 one.)

**Comment by ntonnaett** [comment]
In wayland window decorations are the domain of the client. KDE Plasma offers a wayland extension that Qt uses to offload the rendering of the window decorations. If the wayland compositor doesn't offer this extension (like mutter), the client has to fallback to client side decorations. So it looks as if this issues only occurs when the window decorations are rendered in the main loop of jacktrip. It doesn't happen in every view. So there might be something blocking that shouldn't that's not there in the Logging in… view but in the Overview and the Settings view.

**Comment by psiborg112** [comment]
Everything is done asynchronously, so there shouldn't be anything that blocks. Unless there's something happening within the Qt libraries that's blocking?

**Comment by ntonnaett** [comment]
An unfinished future can block too. What type of asynchronicity did you use?

**Comment by psiborg112** [comment]
The same Qt signal/slot mechanisms that we use everywhere else in the project. Which is the main way that the c++ and qml code communicate. So, now that I think of it, if our event loop was blocking then we'd have much bigger problems than dodgy window decorations across all of our supported platforms.

**Comment by forsythac** [comment]
Is the app functional on Linux? Or does this issue prevent it from operating? It's not clear to me the severity of this issue.

**Comment by psiborg112** [comment]
I can't recreate it, so I don't know. I don't think it should block release though. Worst case scenario, we should make a build without the virtual studio component that we can recommend for Wayland users who are experiencing issues. (It works perfectly fine on linux for me because I use X11, and when testing on Wayland I have a window manager that implements server side window decorations. This really only seems to be a problem for compositors like mutter and weston that insist on having the client handle window decorations, and it seems like an issue between Qt and the compositor that we may not be able to easily resolve.)

**Comment by mikedickey** [comment]
I just tested on my laptop with Fedora 35, using Wayland, and it seems to work perfectly fine for me.

**Comment by ntonnaett** [comment]
I don't know why but in your [comment](https://github.com/jacktrip/jacktrip/issues/561#issuecomment-1125536200) it looks like Qt defaults to xcb on your system. Did you install Qt5 from somewhere else than the Fedora repos? Did you make sure that you use the wayland plugin?

**Comment by ntonnaett** [comment]
> Is the app functional on Linux? Or does this issue prevent it from operating? It's not clear to me the severity of this issue.

I always get a TCP connection error when trying to connect with the virtual studio view. But that's another issue. I think we should ignore this issue and just live with these bugs until we switch to qt6.

**Comment by psiborg112** [comment]
Well that's a much bigger issue than window decorations. Since it shares the same connection code that's used in every other iteration of the interface (QWidget/command line), I'm guessing that somehow the wrong host or port information might be getting passed through if it's not some sort of network issue. Not sure how though since there shouldn't be the opportunity for the qml and c++ data to get out of sync. It might be worth adding some print debugging statements to see what values you have for studioInfo->host() and studioinfo->port() in VirtualStudio::completeConnection. (Could also be useful checking what studioinfo->name() gives you to make sure it's actually the server that you've chosen that we're attempting to connect to.)

**Comment by mattahorton** [comment]
Are you still seeing this? I installed Fedora 36 which uses Gnome 42/Wayland this week and didn't have any issues.
