### ISSUE TITLE
VS: changing selected device does not save properly

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#570]
1. Connect to a studio
2. Disconnect
3. Go to settings
4. Change device selection
5. Connect to studio again

It will display the original devices that you had selected the first time that you connected

**Comment by psiborg112** [comment]
My bad. That'll be fixed in one of the changes in #569. Thought the only place we were showing that information was in the combo boxes on the settings page, which were always up to date and didn't require signalling when saving settings. (A case of premature optimization.) Now that we have combo boxes across multiple screens that has changed. (And will fix this issue.)

**Comment by mattahorton** [comment]
Yeah. I fixed this one today. It was bugging me too. 😅
