### ISSUE TITLE
Unplugging input/output device while connected causes app to hang

### ISSUE THREAD

**Issue by nwang92** [jacktrip/jacktrip#616]
To reproduce:
* Open the app in Virtual Studio mode
* Use some non-default device as either your input or output device
* Connect to any studio
* Unplug the physical device from your computer
* Wait ~1m and the app will hang

Once the app is in this state, you lose the ability leave the studio or close the app (basically no interaction whatsoever). I have to force quit or kill the process manually.

**Comment by cchafe** [comment]
RtAudio or Jack (or both)?

**Comment by cchafe** [comment]
Fails the same with Fedora 35, RtAudio, meson build, USB audio interface
...after unplugging the interface, continuous messages to terminal...
RtApiAlsa::callbackEvent: audio read error, No such device.
RtApiAlsa::callbackEvent: audio read error, No such device.
RtApiAlsa::callbackEvent: audio read error, No such device.

Closing the window doesn't close it but the OS responds with a force quit of 
unresponsive application dialog which is enough to kill it.

**Comment by cchafe** [comment]
Same hang with Jack (except no msgs printing).

**Comment by JanSto1995** [comment]
Thx for posting this here, Nelson. It's be great if that audio read error could be monitored by the program and, once occurring:
- Show that error/pop-up message (along the lines of "It seems like your selected audio device is no longer connected. Please choose a new device!") and/or
- automatically open the setup window again (and automatically refresh devices)

**Comment by JanSto1995** [comment]
After some more testing, here are my findings (on Mac running Catalina 10.15.7 with a Steinberg824 audio interface):
- App crashes as described above when selecting my audio interface for both Input and Output and disconnecting it
- App also crashes when selecting another device (internal MacBook mic) as Input, and my audio interface as Output
- App does NOT crash when selecting my audio interface only as Input, and other device (internal MacBook speakers) as Output

It thus seems like the app crashes when the Output device is disconnected and continues to run when only the input device is changed.. hope this helps

**Comment by ntonnaett** [comment]
I think we didn't implement any callbacks for this. In RtAudio there is [RtAudioErrorCallback](http://www.music.mcgill.ca/~gary/rtaudio/RtAudio_8h.html#aee31aa6f8714fc17b8f99e8ac2ca07fa). For JACK it's probably [JackInfoShutdownCallback](https://jackaudio.org/api/group__ClientCallbacks.html#gaf54d9f133267170ef1e6ce5219d24dd4).

**Comment by psiborg112** [comment]
We do have callbacks for JACK (jack_on_shutdown). It just looks like it isn't called when a device is unplugged. (The QjackCtl interface shows the server as still running. Will have to look through the error messages that are output when I get a chance. Could be a while, so if someone else gets to it first, all good.)

**Comment by mattahorton** [comment]
It looks like the behavior to close the stream automatically when devices are removed was added to RtAudio in June. We downgraded due to an issue with ASIO on default devices, but @dyfer's getDefaultDevice issue [was fixed on Nov 12](https://github.com/thestk/rtaudio/issues/323).

I think we should start by upgrading back to the latest RtAudio. I have a branch I'm working on that adds the callbacks @ntonnaett mentioned above, but RtAudio still hangs.

**Comment by mattahorton** [comment]
I should say, I don't use JACK as I don't have a need to. I will install it and test the behavior there.

**Comment by ntonnaett** [comment]
The latest RtAudio version 5.2 was released in Nov 2021. Switching to RtAudio 6 means at least changing error handling because there are no exceptions anymore. And we shouldn't do this before there is a final release.

**Comment by mattahorton** [comment]
@ntonnaett that fix _is_ in 5.2 if we wanted to move up to 5.2

**Comment by ntonnaett** [comment]
But the getDefaultDevice fix is in 5.2. So upgrading to the latest should be fine.

**Comment by mattahorton** [comment]
So the draft PR #701 tries to fix some of this. RtAudio still has the hang behavior in both GUI modes. Seems fixed in JACK.

If anyone has ideas on how to fix this without using an unfinished version of RtAudio, I'm all ears. I did go ahead and update to RtAudio 5.2, but like @ntonnaett said, 6 is not finished and will be a larger effort to change how RtAudio errors are handled. Version 6 will close the stream for disconnected devices but only on macOS. So we'll need to come up with a solution ourselves for Windows and Linux anyway.

My guess is that during processing of audio we could detect if the active device still exists?

**Comment by mikedickey** [comment]
[This PR ](https://github.com/jacktrip/jacktrip/pull/1118) updates to rtaudio 6.0.1. Unfortunately, it doesn't seem to magically solve the issue. I did notice that we now get a new error message on console when you unplug devices:

```
RtApiCore: the stream device was disconnected (and closed)!
```

So maybe there is a way we can catch and handle it more gracefully now?

**Comment by nwang92** [comment]
This is done with 2.0.0
