### ISSUE TITLE
manjaro missing dependencies

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#619]
1.6.0 in manjaro testing needs qt5-quickcontrols2, qt5-grapicaleffects

**Comment by cchafe** [comment]
also needs to be built with rtaudio

**Comment by dyfer** [comment]
Thanks @cchafe 
- Is this for the Linux static build?
- We can easily turn on RtAudio in the build, but functionally a prerequisite for this would be to add backend switching (Currently RtAudio uses the first backend from the ones that I available - I can't remember in which order i.e. which one would be active)

**Comment by dyfer** [comment]
Just to clarify: do we need to add these packages to Linux build instructions? 
Should we have a separate section for Manjaro Linux? How about Arch?

**Comment by ntonnaett** [comment]
@dvzrv The JackTrip arch packages are missing some runtime dependencies. Do you mind adding these?

**Comment by dvzrv** [comment]
@ntonnaett why does the build not fail, if they are missing?

@cchafe Manjaro in fact only reuses all packages from Arch Linux and therefore can not be considered as the target of this ticket :laughing:

For Arch Linux I have disabled the rtaudio build since 1.4.0 (https://github.com/archlinux/svntogit-community/commit/5f7b376b1348f9fe2232baf99f8746b96f19a7a6) but I don't remember why anymore. I can check to build with it.

**Comment by dvzrv** [comment]
> why does the build not fail, if they are missing?

To answer my own question: Dependency handling seems to still be done using a qmake file instead of fully relying on meson, which seems to be the problem in regards to detection and failing on missing dependencies.
Either way: The build does not link against the shared libraries provided by qt5-quickcontrols2 and qt5-graphicaleffects only provides qml files (so no linking anyhow). How are these dependencies used during runtime?
For proper inclusion and discoverability, they should be searched for during build time.

> For Arch Linux I have disabled the rtaudio build since 1.4.0 (https://github.com/archlinux/svntogit-community/commit/5f7b376b1348f9fe2232baf99f8746b96f19a7a6) but I don't remember why anymore.

IIRC, the jack and rtaudio backend could not be enabled both when building. This restriction seems to be lifted though.

**Comment by ntonnaett** [comment]
Meson doesn't rely on qmake for dependency handling. With Meson we can't do ahead-of-time compilation of QMLs. So those are runtime dependencies.

**Comment by ntonnaett** [comment]
Thanks for adding those things! Looks like this issue can be closed.

BTW the updater is disabled by default on Linux.
