### ISSUE TITLE
Build JackTrip for i686

### ISSUE THREAD

**Issue by forsythac** [jacktrip/jacktrip#725]
### Discussed in https://github.com/jacktrip/jacktrip/discussions/721

<div type='discussions-op-text'>

<sup>Originally posted by **forsythac** September  1, 2022</sup>
Does JackTrip support 32bit Windows machines? Do we need different executables to support them?</div>

Seems that we need to clarify whether JackTrip is supported on 32bit OS. This issue was reported from some students trying to use JackTrip with a small Acer laptop running Windows 10 32bit

**Comment by ntonnaett** [comment]
x86 machines that only support 32bit are very old. amd64 was introduced around twenty years ago. Fedora even removed their 32bit compatibility packages. Nevertheless building 32bit versions of JackTrip shouldn't be a problem. I'm just wondering why people haven't switched to a 64bit Windows version yet. What hardware are they using?

You mentioned in the discussion that JackTrip is installed in the 32bit location on Windows. Is this just your assumption because there's x86 in the name?

**Comment by forsythac** [comment]
I'm a Windows user myself and it currently installs in Program Files (x86) by default
<img width="744" alt="image" src="https://user-images.githubusercontent.com/3578658/188764661-9b1b16f3-1248-47cf-856c-6e1658d0847c.png">

**Comment by forsythac** [comment]
Hardware is an Acer laptop being used for schools. details from the user:

Acer Computer
Installed RAM: 2.00 GB
System type: 32-bit operating system, x64 based processor

Windows specifications
Edition: Windows 10 Pro
Version: 21H2
Installed on: 5/10/22
OS build: 19044.1766

**Comment by ntonnaett** [comment]
> I'm a Windows user myself and it currently installs in Program Files (x86) by default <img alt="image" width="744" src="https://user-images.githubusercontent.com/3578658/188764661-9b1b16f3-1248-47cf-856c-6e1658d0847c.png">

x86 doesn't mean it is 32bit. AMD64/x86-64 and IA-32 are both extensions to the original 16bit ISA.

If they have a 64bit processor, they should install a 64bit Windows or Linux.

**Comment by ntonnaett** [comment]
There seems to be no official documentation about install locations, but after a short search I found [this](https://stackoverflow.com/questions/63281973/wix-msi-default-installation-location-is-32bit-instead-of-64bit-program-files). Seems we have to tell WiX that the platform is x64.

**Comment by dyfer** [comment]
To answer the original question - we only build a 64-bit version of JackTrip for Windows. It should be possible to build a 32-bit version though. As @ntonnaett pointed out, the need for that should be fairly limited (though I myself used a 32-bit version of Windows 7/10 in order to maintain compatibility with some ancient software/drivers, but that was a few years back). Having said that, should we add a Windows 32-bit version?

(and yes, JT seems to be incorrectly installed in the `Program Files (x86)` directory)

**Comment by forsythac** [comment]
Is there any downside to using a 32bit version of JackTrip?

**Comment by dyfer** [comment]
> Is there any downside to using a 32bit version of JackTrip?

On a 64-bit operating system? Others probably know more about it, but AFAIU:
- it can't address more than ~3.6GB of memory
- needs to run through a translation layer
- eventually it will stop working
  - for reference, on Apple hardware the last macOS to support running 32-bit apps was 10.14 released in 2018

**Comment by ntonnaett** [comment]
There's no good reason to run 32bit software on a 64bit OS, if you can avoid it. The performance is usually better with 64bit. The memory usage increases because pointers are double the size for 64bit. I don't think any other type changed in size with x86-64. JackTrip doesn't use a lot of memory but could benefit from better performance.

32 bit x86 software runs natively on x86-64 CPUs. There's no software translation layer involved. I assume it's the same for arm64, because you can just install a 32bit armv7 OS on those devices. 

[Looks with the Windows 10 license](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-pro-32-bit-digital-licence-to-64-bit/96624427-0b80-4d10-a696-d3793552e424) you can choose if you want to use 32bit or 64bit.

**Comment by dyfer** [comment]
> 32 bit x86 software runs natively on x86-64 CPUs. There's no software translation layer involved.

My impression was that when the OS is 64-bit, it needs some translation layer to run 32-bit apps, to provide proper memory mapping, inter-process communication etc. My my knowledge of that is really minimal.

> [Looks like](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-pro-32-bit-digital-licence-to-64-bit/96624427-0b80-4d10-a696-d3793552e424) you can choose if you want to use 32bit or 64bit with the Windows 10 license.

That would mean they have to re-install the OS, which might be unfeasible for many users.

BTW I still stand by what I said about memory consumption. If everything is 32-bit, it will take up less RAM, AFAIK.

**Comment by SynthiaPayne** [comment]
I'm pretty sure that beginning with Version 1.2.1 in July 2020, a 64-bit 
was required. Hard to believe that was only 2 years ago! That's when I 
did my YouTube series for JackTrip on Windows. Before that I ran 
JackTrip on a 32-bit laptop and found I needed to get a 64-bit to run 1.2

synthia

**Comment by SynthiaPayne** [comment]
Although I’m not sure why my post is appearing weeks late…I have since learned that the 32-bit / 64-bit question can refer to operating systems or processors, and if I understand correctly, modern processors can run a 64-bit operating system as x86? Of course the machine would need to meet other requirements and have a clean install in order to run a 64-bit OS, but if this is the case, it could help out the folks who were not able to install a 64-bit JackTrip on those Acer laptops. Nils, what say ye? Anybody? I’m going to be visiting these folks next week.

**Comment by ntonnaett** [comment]
You can't run 64-bit software on a 32-bit OS. Right now you need to build jacktrip yourself on those platforms.

**Comment by SynthiaPayne** [comment]
Thanks for that confirmation, Nils!
Perhaps a bit off-topic now: I see that the Acer laptops referred to in 
this thread have x64-based processors so they could probably be 
reformatted with a 64-bit operating system. Then they would not have to 
do a 32-bit build. I'll give it a shot.

**Comment by ntonnaett** [comment]
Yes, that's right. You could just install a 64bit OS.

**Comment by ntonnaett** [comment]
@SynthiaPayne Could you help those folks?
