### ISSUE TITLE
Windows Command Window opens when launching JackTrip

### ISSUE THREAD

**Issue by SynthiaPayne** [jacktrip/jacktrip#801]
Hello All!

With the latest Windows updates on 11/8/2022:
1. 2022-11 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5019980)
2. 2022-11 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5020622)

When launching JackTrip, the Command Window opens. 

![windows update command window](https://user-images.githubusercontent.com/2858155/200914429-8c066efa-8b1d-4809-8880-5356f17950dd.jpg)

**Comment by psiborg112** [comment]
There have been intermittent reports of this happening before. It's a quirk of how windows handles command line programs compared to the other platforms. Because we still want JackTrip to be able to run from the command line, it gets treated by windows as a command line program and so a prompt is automatically spawned. The initial code in the app detects whether the user wants to run with the GUI or not, and if we do, it detaches from the command line and closes the window. (It's why occasionally when you run JackTrip you might briefly see a command prompt appear and then disappear.) For some reason, under some circumstances in Windows 11 the FreeConsole() function that gets called in main to dispatch with the command window doesn't work as expected.

I can't troubleshoot this myself as I'm still on Windows 10. (Should probably upgrade soon, but already made the mistake recently of upgrading to Ventura and am now waiting for macports to catch up. So don't want to go through that again in a hurry.) But that's the place to start looking. (And to check the output of isRunFromCmd() in main.cpp as well.)

**Comment by psiborg112** [comment]
Finally on Windows 11 and can't reproduce. Is this still an issue?

**Comment by SynthiaPayne** [comment]
for me it is still happening on 1.8, yes.

**Comment by psiborg112** [comment]
Thanks for confirming although annoying that I can't reproduce it for some reason. I know it's a pain, but would you be able to test my build from [this page](https://www.psi-borg.org/other-dev.html) if you have a moment? That'll at least show whether it's a build issue or a code issue.

**Comment by SynthiaPayne** [comment]
I installed the version from the link below and the command window still 
opens.

**Comment by psiborg112** [comment]
Thanks. So it's a code and not a build issue. But for some reason not one that I can trigger on my computer.

**Comment by SynthiaPayne** [comment]
@mikedickey did some digging and found out that Microsoft will eventually provide an update to mitigate this issue. He posted on the JackTrip Community Forums - https://community.jacktrip.org/t/how-to-get-rid-of-the-weakjack-warning-on-windows-11/557

I'll close it for now and hopefully the issue is resolved with an update.

Thanks all!

**Comment by psiborg112** [comment]
Glad that we've found the culprit and that it's a windows bug.
