### ISSUE TITLE
VirtualStudio interface issue with Qt 5.12

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#852]
After building locally on Ubuntu 20.04, I can't load the VS interface, despite the app compiling properly and launching. I'm guessing this has to do with compatibility with Qt 5.12.8 (the version available for Ubuntu 20.04) and Qt Quick. 

I'm getting a blank screen (no way to go through the setup or switch to classic interface) and the following output:

``` 
$ builddir/jacktrip
qrc:/vs/vs.qml:102:5: Type Setup unavailable
qrc:/vs/Setup.qml:603:26: Expected token `:'
SSL Library: OpenSSL 1.1.1f 31 Mar 2020
Log file location (...)
```

_Originally posted by @dyfer in https://github.com/jacktrip/jacktrip/issues/845#issuecomment-1353224096_

**Comment by dyfer** [comment]
@ntonnaett I assume this is a suggestion for the Linux static build, correct?

I just want to make sure everybody is aware - this issue means that JackTrip with VirtualStudio cannot be run on older Ubuntu (20.04LTS and earlier - that's one before the latest LTS version) _even if compiled locally_(*). My preference would be to fix compatibility with Qt 5.12 and have appropriate solution to use QuickControls only when compiling for Qt >=5.15. 

But since apparently nobody noticed/complained about it until now, then maybe there's no real-world need for it. I just want to make sure everybody is aware of the consequences of not supporting Qt 5.12 anymore. I'm happy to update the static Linux build to Qt 5.15 if that's what we want.
(Also, this doesn't affect Windows and macOS where we only use Qt 5.15).

(*) maybe it's possible to install QT 5.15 from a PPA on Ubuntu 20.04, but I'm not sure how practical or problematic that is.

**Comment by ntonnaett** [comment]
Maybe we can avoid the required property feature and stay with 5.12 for now. QuickControls isn't the problem here. With ahead-of-time compilation enabled, we would have catched that at compile time.

As you said, nobody complained until now. We don't have any clue about what distributions are actually used. We should try to serve as many distributions as possible, but we should also avoid investing time that doesn't serve anybody. IMHO we should use the same Qt version on all platforms. Maybe something like distrobox or toolbx is a good way to serve old distributions. I'll look into that when I have time. The OSB path wouldn't have helped here because those packages depend on the qt version of the distribution.

**Comment by dyfer** [comment]
Virtual studio interface still requires QT 5.12, but in #888 we will get a working static Linux build that should run even on older systems, so I assume this doesn't have to be addressed.
